/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.br.kafka.dto.avro.personagem;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PersonagemStarWars extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2769955429591440235L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PersonagemStarWars\",\"namespace\":\"com.br.kafka.dto.avro.personagem\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"nome\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"altura\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"peso\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"corCabelo\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"corPele\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"corOlhos\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"anoNascimento\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"genero\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"urlImagem\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"comentario\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PersonagemStarWars> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PersonagemStarWars> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PersonagemStarWars> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PersonagemStarWars> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PersonagemStarWars> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PersonagemStarWars to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PersonagemStarWars from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PersonagemStarWars instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PersonagemStarWars fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private java.lang.String nome;
  private java.lang.String altura;
  private java.lang.String peso;
  private java.lang.String corCabelo;
  private java.lang.String corPele;
  private java.lang.String corOlhos;
  private java.lang.String anoNascimento;
  private java.lang.String genero;
  private java.lang.String urlImagem;
  private java.lang.String comentario;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PersonagemStarWars() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param nome The new value for nome
   * @param altura The new value for altura
   * @param peso The new value for peso
   * @param corCabelo The new value for corCabelo
   * @param corPele The new value for corPele
   * @param corOlhos The new value for corOlhos
   * @param anoNascimento The new value for anoNascimento
   * @param genero The new value for genero
   * @param urlImagem The new value for urlImagem
   * @param comentario The new value for comentario
   */
  public PersonagemStarWars(java.lang.Integer id, java.lang.String nome, java.lang.String altura, java.lang.String peso, java.lang.String corCabelo, java.lang.String corPele, java.lang.String corOlhos, java.lang.String anoNascimento, java.lang.String genero, java.lang.String urlImagem, java.lang.String comentario) {
    this.id = id;
    this.nome = nome;
    this.altura = altura;
    this.peso = peso;
    this.corCabelo = corCabelo;
    this.corPele = corPele;
    this.corOlhos = corOlhos;
    this.anoNascimento = anoNascimento;
    this.genero = genero;
    this.urlImagem = urlImagem;
    this.comentario = comentario;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return nome;
    case 2: return altura;
    case 3: return peso;
    case 4: return corCabelo;
    case 5: return corPele;
    case 6: return corOlhos;
    case 7: return anoNascimento;
    case 8: return genero;
    case 9: return urlImagem;
    case 10: return comentario;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: nome = value$ != null ? value$.toString() : null; break;
    case 2: altura = value$ != null ? value$.toString() : null; break;
    case 3: peso = value$ != null ? value$.toString() : null; break;
    case 4: corCabelo = value$ != null ? value$.toString() : null; break;
    case 5: corPele = value$ != null ? value$.toString() : null; break;
    case 6: corOlhos = value$ != null ? value$.toString() : null; break;
    case 7: anoNascimento = value$ != null ? value$.toString() : null; break;
    case 8: genero = value$ != null ? value$.toString() : null; break;
    case 9: urlImagem = value$ != null ? value$.toString() : null; break;
    case 10: comentario = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'nome' field.
   * @return The value of the 'nome' field.
   */
  public java.lang.String getNome() {
    return nome;
  }


  /**
   * Sets the value of the 'nome' field.
   * @param value the value to set.
   */
  public void setNome(java.lang.String value) {
    this.nome = value;
  }

  /**
   * Gets the value of the 'altura' field.
   * @return The value of the 'altura' field.
   */
  public java.lang.String getAltura() {
    return altura;
  }


  /**
   * Sets the value of the 'altura' field.
   * @param value the value to set.
   */
  public void setAltura(java.lang.String value) {
    this.altura = value;
  }

  /**
   * Gets the value of the 'peso' field.
   * @return The value of the 'peso' field.
   */
  public java.lang.String getPeso() {
    return peso;
  }


  /**
   * Sets the value of the 'peso' field.
   * @param value the value to set.
   */
  public void setPeso(java.lang.String value) {
    this.peso = value;
  }

  /**
   * Gets the value of the 'corCabelo' field.
   * @return The value of the 'corCabelo' field.
   */
  public java.lang.String getCorCabelo() {
    return corCabelo;
  }


  /**
   * Sets the value of the 'corCabelo' field.
   * @param value the value to set.
   */
  public void setCorCabelo(java.lang.String value) {
    this.corCabelo = value;
  }

  /**
   * Gets the value of the 'corPele' field.
   * @return The value of the 'corPele' field.
   */
  public java.lang.String getCorPele() {
    return corPele;
  }


  /**
   * Sets the value of the 'corPele' field.
   * @param value the value to set.
   */
  public void setCorPele(java.lang.String value) {
    this.corPele = value;
  }

  /**
   * Gets the value of the 'corOlhos' field.
   * @return The value of the 'corOlhos' field.
   */
  public java.lang.String getCorOlhos() {
    return corOlhos;
  }


  /**
   * Sets the value of the 'corOlhos' field.
   * @param value the value to set.
   */
  public void setCorOlhos(java.lang.String value) {
    this.corOlhos = value;
  }

  /**
   * Gets the value of the 'anoNascimento' field.
   * @return The value of the 'anoNascimento' field.
   */
  public java.lang.String getAnoNascimento() {
    return anoNascimento;
  }


  /**
   * Sets the value of the 'anoNascimento' field.
   * @param value the value to set.
   */
  public void setAnoNascimento(java.lang.String value) {
    this.anoNascimento = value;
  }

  /**
   * Gets the value of the 'genero' field.
   * @return The value of the 'genero' field.
   */
  public java.lang.String getGenero() {
    return genero;
  }


  /**
   * Sets the value of the 'genero' field.
   * @param value the value to set.
   */
  public void setGenero(java.lang.String value) {
    this.genero = value;
  }

  /**
   * Gets the value of the 'urlImagem' field.
   * @return The value of the 'urlImagem' field.
   */
  public java.lang.String getUrlImagem() {
    return urlImagem;
  }


  /**
   * Sets the value of the 'urlImagem' field.
   * @param value the value to set.
   */
  public void setUrlImagem(java.lang.String value) {
    this.urlImagem = value;
  }

  /**
   * Gets the value of the 'comentario' field.
   * @return The value of the 'comentario' field.
   */
  public java.lang.String getComentario() {
    return comentario;
  }


  /**
   * Sets the value of the 'comentario' field.
   * @param value the value to set.
   */
  public void setComentario(java.lang.String value) {
    this.comentario = value;
  }

  /**
   * Creates a new PersonagemStarWars RecordBuilder.
   * @return A new PersonagemStarWars RecordBuilder
   */
  public static com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder newBuilder() {
    return new com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder();
  }

  /**
   * Creates a new PersonagemStarWars RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PersonagemStarWars RecordBuilder
   */
  public static com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder newBuilder(com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder other) {
    if (other == null) {
      return new com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder();
    } else {
      return new com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder(other);
    }
  }

  /**
   * Creates a new PersonagemStarWars RecordBuilder by copying an existing PersonagemStarWars instance.
   * @param other The existing instance to copy.
   * @return A new PersonagemStarWars RecordBuilder
   */
  public static com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder newBuilder(com.br.kafka.dto.avro.personagem.PersonagemStarWars other) {
    if (other == null) {
      return new com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder();
    } else {
      return new com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder(other);
    }
  }

  /**
   * RecordBuilder for PersonagemStarWars instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PersonagemStarWars>
    implements org.apache.avro.data.RecordBuilder<PersonagemStarWars> {

    private int id;
    private java.lang.String nome;
    private java.lang.String altura;
    private java.lang.String peso;
    private java.lang.String corCabelo;
    private java.lang.String corPele;
    private java.lang.String corOlhos;
    private java.lang.String anoNascimento;
    private java.lang.String genero;
    private java.lang.String urlImagem;
    private java.lang.String comentario;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nome)) {
        this.nome = data().deepCopy(fields()[1].schema(), other.nome);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.altura)) {
        this.altura = data().deepCopy(fields()[2].schema(), other.altura);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.peso)) {
        this.peso = data().deepCopy(fields()[3].schema(), other.peso);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.corCabelo)) {
        this.corCabelo = data().deepCopy(fields()[4].schema(), other.corCabelo);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.corPele)) {
        this.corPele = data().deepCopy(fields()[5].schema(), other.corPele);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.corOlhos)) {
        this.corOlhos = data().deepCopy(fields()[6].schema(), other.corOlhos);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.anoNascimento)) {
        this.anoNascimento = data().deepCopy(fields()[7].schema(), other.anoNascimento);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.genero)) {
        this.genero = data().deepCopy(fields()[8].schema(), other.genero);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.urlImagem)) {
        this.urlImagem = data().deepCopy(fields()[9].schema(), other.urlImagem);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.comentario)) {
        this.comentario = data().deepCopy(fields()[10].schema(), other.comentario);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing PersonagemStarWars instance
     * @param other The existing instance to copy.
     */
    private Builder(com.br.kafka.dto.avro.personagem.PersonagemStarWars other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nome)) {
        this.nome = data().deepCopy(fields()[1].schema(), other.nome);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.altura)) {
        this.altura = data().deepCopy(fields()[2].schema(), other.altura);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.peso)) {
        this.peso = data().deepCopy(fields()[3].schema(), other.peso);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.corCabelo)) {
        this.corCabelo = data().deepCopy(fields()[4].schema(), other.corCabelo);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.corPele)) {
        this.corPele = data().deepCopy(fields()[5].schema(), other.corPele);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.corOlhos)) {
        this.corOlhos = data().deepCopy(fields()[6].schema(), other.corOlhos);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.anoNascimento)) {
        this.anoNascimento = data().deepCopy(fields()[7].schema(), other.anoNascimento);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.genero)) {
        this.genero = data().deepCopy(fields()[8].schema(), other.genero);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.urlImagem)) {
        this.urlImagem = data().deepCopy(fields()[9].schema(), other.urlImagem);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.comentario)) {
        this.comentario = data().deepCopy(fields()[10].schema(), other.comentario);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nome' field.
      * @return The value.
      */
    public java.lang.String getNome() {
      return nome;
    }


    /**
      * Sets the value of the 'nome' field.
      * @param value The value of 'nome'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setNome(java.lang.String value) {
      validate(fields()[1], value);
      this.nome = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nome' field has been set.
      * @return True if the 'nome' field has been set, false otherwise.
      */
    public boolean hasNome() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nome' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearNome() {
      nome = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'altura' field.
      * @return The value.
      */
    public java.lang.String getAltura() {
      return altura;
    }


    /**
      * Sets the value of the 'altura' field.
      * @param value The value of 'altura'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setAltura(java.lang.String value) {
      validate(fields()[2], value);
      this.altura = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'altura' field has been set.
      * @return True if the 'altura' field has been set, false otherwise.
      */
    public boolean hasAltura() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'altura' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearAltura() {
      altura = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'peso' field.
      * @return The value.
      */
    public java.lang.String getPeso() {
      return peso;
    }


    /**
      * Sets the value of the 'peso' field.
      * @param value The value of 'peso'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setPeso(java.lang.String value) {
      validate(fields()[3], value);
      this.peso = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'peso' field has been set.
      * @return True if the 'peso' field has been set, false otherwise.
      */
    public boolean hasPeso() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'peso' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearPeso() {
      peso = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'corCabelo' field.
      * @return The value.
      */
    public java.lang.String getCorCabelo() {
      return corCabelo;
    }


    /**
      * Sets the value of the 'corCabelo' field.
      * @param value The value of 'corCabelo'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setCorCabelo(java.lang.String value) {
      validate(fields()[4], value);
      this.corCabelo = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'corCabelo' field has been set.
      * @return True if the 'corCabelo' field has been set, false otherwise.
      */
    public boolean hasCorCabelo() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'corCabelo' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearCorCabelo() {
      corCabelo = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'corPele' field.
      * @return The value.
      */
    public java.lang.String getCorPele() {
      return corPele;
    }


    /**
      * Sets the value of the 'corPele' field.
      * @param value The value of 'corPele'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setCorPele(java.lang.String value) {
      validate(fields()[5], value);
      this.corPele = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'corPele' field has been set.
      * @return True if the 'corPele' field has been set, false otherwise.
      */
    public boolean hasCorPele() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'corPele' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearCorPele() {
      corPele = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'corOlhos' field.
      * @return The value.
      */
    public java.lang.String getCorOlhos() {
      return corOlhos;
    }


    /**
      * Sets the value of the 'corOlhos' field.
      * @param value The value of 'corOlhos'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setCorOlhos(java.lang.String value) {
      validate(fields()[6], value);
      this.corOlhos = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'corOlhos' field has been set.
      * @return True if the 'corOlhos' field has been set, false otherwise.
      */
    public boolean hasCorOlhos() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'corOlhos' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearCorOlhos() {
      corOlhos = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'anoNascimento' field.
      * @return The value.
      */
    public java.lang.String getAnoNascimento() {
      return anoNascimento;
    }


    /**
      * Sets the value of the 'anoNascimento' field.
      * @param value The value of 'anoNascimento'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setAnoNascimento(java.lang.String value) {
      validate(fields()[7], value);
      this.anoNascimento = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'anoNascimento' field has been set.
      * @return True if the 'anoNascimento' field has been set, false otherwise.
      */
    public boolean hasAnoNascimento() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'anoNascimento' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearAnoNascimento() {
      anoNascimento = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'genero' field.
      * @return The value.
      */
    public java.lang.String getGenero() {
      return genero;
    }


    /**
      * Sets the value of the 'genero' field.
      * @param value The value of 'genero'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setGenero(java.lang.String value) {
      validate(fields()[8], value);
      this.genero = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'genero' field has been set.
      * @return True if the 'genero' field has been set, false otherwise.
      */
    public boolean hasGenero() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'genero' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearGenero() {
      genero = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'urlImagem' field.
      * @return The value.
      */
    public java.lang.String getUrlImagem() {
      return urlImagem;
    }


    /**
      * Sets the value of the 'urlImagem' field.
      * @param value The value of 'urlImagem'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setUrlImagem(java.lang.String value) {
      validate(fields()[9], value);
      this.urlImagem = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'urlImagem' field has been set.
      * @return True if the 'urlImagem' field has been set, false otherwise.
      */
    public boolean hasUrlImagem() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'urlImagem' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearUrlImagem() {
      urlImagem = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'comentario' field.
      * @return The value.
      */
    public java.lang.String getComentario() {
      return comentario;
    }


    /**
      * Sets the value of the 'comentario' field.
      * @param value The value of 'comentario'.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder setComentario(java.lang.String value) {
      validate(fields()[10], value);
      this.comentario = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'comentario' field has been set.
      * @return True if the 'comentario' field has been set, false otherwise.
      */
    public boolean hasComentario() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'comentario' field.
      * @return This builder.
      */
    public com.br.kafka.dto.avro.personagem.PersonagemStarWars.Builder clearComentario() {
      comentario = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PersonagemStarWars build() {
      try {
        PersonagemStarWars record = new PersonagemStarWars();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.nome = fieldSetFlags()[1] ? this.nome : (java.lang.String) defaultValue(fields()[1]);
        record.altura = fieldSetFlags()[2] ? this.altura : (java.lang.String) defaultValue(fields()[2]);
        record.peso = fieldSetFlags()[3] ? this.peso : (java.lang.String) defaultValue(fields()[3]);
        record.corCabelo = fieldSetFlags()[4] ? this.corCabelo : (java.lang.String) defaultValue(fields()[4]);
        record.corPele = fieldSetFlags()[5] ? this.corPele : (java.lang.String) defaultValue(fields()[5]);
        record.corOlhos = fieldSetFlags()[6] ? this.corOlhos : (java.lang.String) defaultValue(fields()[6]);
        record.anoNascimento = fieldSetFlags()[7] ? this.anoNascimento : (java.lang.String) defaultValue(fields()[7]);
        record.genero = fieldSetFlags()[8] ? this.genero : (java.lang.String) defaultValue(fields()[8]);
        record.urlImagem = fieldSetFlags()[9] ? this.urlImagem : (java.lang.String) defaultValue(fields()[9]);
        record.comentario = fieldSetFlags()[10] ? this.comentario : (java.lang.String) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PersonagemStarWars>
    WRITER$ = (org.apache.avro.io.DatumWriter<PersonagemStarWars>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PersonagemStarWars>
    READER$ = (org.apache.avro.io.DatumReader<PersonagemStarWars>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeString(this.nome);

    if (this.altura == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.altura);
    }

    if (this.peso == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.peso);
    }

    if (this.corCabelo == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.corCabelo);
    }

    if (this.corPele == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.corPele);
    }

    if (this.corOlhos == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.corOlhos);
    }

    if (this.anoNascimento == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.anoNascimento);
    }

    if (this.genero == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.genero);
    }

    if (this.urlImagem == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.urlImagem);
    }

    if (this.comentario == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.comentario);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.nome = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.altura = null;
      } else {
        this.altura = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.peso = null;
      } else {
        this.peso = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.corCabelo = null;
      } else {
        this.corCabelo = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.corPele = null;
      } else {
        this.corPele = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.corOlhos = null;
      } else {
        this.corOlhos = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.anoNascimento = null;
      } else {
        this.anoNascimento = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.genero = null;
      } else {
        this.genero = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.urlImagem = null;
      } else {
        this.urlImagem = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.comentario = null;
      } else {
        this.comentario = in.readString();
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.nome = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.altura = null;
          } else {
            this.altura = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.peso = null;
          } else {
            this.peso = in.readString();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.corCabelo = null;
          } else {
            this.corCabelo = in.readString();
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.corPele = null;
          } else {
            this.corPele = in.readString();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.corOlhos = null;
          } else {
            this.corOlhos = in.readString();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.anoNascimento = null;
          } else {
            this.anoNascimento = in.readString();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.genero = null;
          } else {
            this.genero = in.readString();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.urlImagem = null;
          } else {
            this.urlImagem = in.readString();
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.comentario = null;
          } else {
            this.comentario = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










